# Generated by Django 5.2.6 on 2025-09-22 09:45

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=128)),
                ('body', tinymce.models.HTMLField()),
                ('display_on_home', models.BooleanField(default=False, help_text='Display this article on the home page')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-posted_on'],
            },
        ),
    ]
