# Generated by Django 5.2.6 on 2025-09-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'home_team'], name='core_game_season__ca42d5_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'away_team'], name='core_game_season__202f56_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['home_score', 'away_score'], name='core_game_home_sc_770253_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['starts_at'], name='core_game_starts__5d1559_idx'),
        ),
    ]
