# Generated by Django 5.2.6 on 2025-09-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='tie_breaker_rank',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='stats',
            name='tie_breaker_reason',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='stats',
            name='tie_breaker_symbol',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
