# Generated by Django 5.2.6 on 2025-09-22 09:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stats_tie_breaker_rank_stats_tie_breaker_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='biography',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
