# Generated by Django 5.2.6 on 2025-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_news_body_alter_team_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='display_on_home',
            field=models.BooleanField(default=False, help_text='Display this article on the home page'),
        ),
    ]
