# Generated by Django 5.2.6 on 2025-09-22 09:45

from django.db import migrations


def copy_categories_to_gallery(apps, schema_editor):
    """Copy category data from core to gallery app"""
    # Get the models from the old and new apps
    CoreCategory = apps.get_model('core', 'Category')
    GalleryCategory = apps.get_model('gallery', 'Category')

    # Copy all categories
    for category in CoreCategory.objects.all():
        GalleryCategory.objects.create(
            id=category.id,
            name=category.name,
            slug=category.slug
        )


def copy_photos_to_gallery(apps, schema_editor):
    """Copy photo data from core to gallery app"""
    # Get the models from the old and new apps
    CorePhoto = apps.get_model('core', 'Photo')
    GalleryPhoto = apps.get_model('gallery', 'Photo')
    GalleryCategory = apps.get_model('gallery', 'Category')

    # Copy all photos
    for photo in CorePhoto.objects.all():
        category = GalleryCategory.objects.get(id=photo.category_id)
        GalleryPhoto.objects.create(
            id=photo.id,
            title=photo.title,
            description=photo.description,
            image=photo.image,
            uploaded_at=photo.uploaded_at,
            category=category
        )


def copy_news_to_news_app(apps, schema_editor):
    """Copy news data from core to news app"""
    # Get the models from the old and new apps
    CoreNews = apps.get_model('core', 'News')
    NewsNews = apps.get_model('news', 'News')

    # Copy all news
    for news in CoreNews.objects.all():
        NewsNews.objects.create(
            id=news.id,
            posted_on=news.posted_on,
            subject=news.subject,
            body=news.body,
            display_on_home=getattr(news, 'display_on_home', False)
        )


def reverse_migration(apps, schema_editor):
    """Reverse the data migration"""
    # Clear the new apps' data
    GalleryCategory = apps.get_model('gallery', 'Category')
    GalleryPhoto = apps.get_model('gallery', 'Photo')
    NewsNews = apps.get_model('news', 'News')

    GalleryCategory.objects.all().delete()
    GalleryPhoto.objects.all().delete()
    NewsNews.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_news_display_on_home'),
        ('gallery', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_categories_to_gallery, reverse_migration),
        migrations.RunPython(copy_photos_to_gallery, reverse_migration),
        migrations.RunPython(copy_news_to_news_app, reverse_migration),
        migrations.DeleteModel(name='Category'),
        migrations.DeleteModel(name='Photo'),
        migrations.DeleteModel(name='News'),
    ]
